// <auto-generated />
using System;
using DestekApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DestekApp.Migrations
{
    [DbContext(typeof(DestekAppDBContext))]
    [Migration("20220114133748_bir")]
    partial class bir
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DestekApp.Models.Adres", b =>
                {
                    b.Property<int>("AdresID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresID"), 1L, 1);

                    b.Property<string>("AdresAdı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresBilgisi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KullanıcıID")
                        .HasColumnType("int");

                    b.HasKey("AdresID");

                    b.HasIndex("KullanıcıID");

                    b.ToTable("Adresler");

                    b.HasData(
                        new
                        {
                            AdresID = 1,
                            AdresAdı = "ev",
                            AdresBilgisi = "Menekşe Mah. Petek Sk. No:31 Kat:3 Daire:6",
                            KullanıcıID = 12
                        },
                        new
                        {
                            AdresID = 2,
                            AdresAdı = "ev",
                            AdresBilgisi = "Küpçüler Mah. Sema Sk. No:28 Kat:2 Daire:2",
                            KullanıcıID = 17
                        },
                        new
                        {
                            AdresID = 3,
                            AdresAdı = "ev",
                            AdresBilgisi = "Eskiler Cad. Fırın Sk. No:38 Pendik",
                            KullanıcıID = 17
                        },
                        new
                        {
                            AdresID = 4,
                            AdresAdı = "ev",
                            AdresBilgisi = "Çakmak Cad. Turgut Özal Sk. No:16 Kat:1 Daire:13",
                            KullanıcıID = 16
                        },
                        new
                        {
                            AdresID = 5,
                            AdresAdı = "ev",
                            AdresBilgisi = "Yedi İklim Mah. Güngören Cad. Lacivert Sk. No:45 Kat:3 Daire:7",
                            KullanıcıID = 57
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Cinsiyet", b =>
                {
                    b.Property<int>("CinsiyetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinsiyetID"), 1L, 1);

                    b.Property<string>("CinsiyetAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CinsiyetID");

                    b.ToTable("Cinsiyetler");

                    b.HasData(
                        new
                        {
                            CinsiyetID = 1,
                            CinsiyetAdı = "Erkek"
                        },
                        new
                        {
                            CinsiyetID = 2,
                            CinsiyetAdı = "Kadın"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Frekans", b =>
                {
                    b.Property<int>("FrekansID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrekansID"), 1L, 1);

                    b.Property<string>("FrekansAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FrekansID");

                    b.ToTable("Frekanslar");

                    b.HasData(
                        new
                        {
                            FrekansID = 1,
                            FrekansAdı = "Tek Seferlik"
                        },
                        new
                        {
                            FrekansID = 2,
                            FrekansAdı = "Günlük"
                        },
                        new
                        {
                            FrekansID = 3,
                            FrekansAdı = "Haftalık"
                        },
                        new
                        {
                            FrekansID = 4,
                            FrekansAdı = "Aylık"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.İhtiyaç", b =>
                {
                    b.Property<int>("İhtiyaçID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("İhtiyaçID"), 1L, 1);

                    b.Property<int>("FrekansID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayıtTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullanıcıID")
                        .HasColumnType("int");

                    b.Property<string>("İhtiyaçAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("İhtiyaçAçıklaması")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("İhtiyaçID");

                    b.HasIndex("FrekansID");

                    b.HasIndex("KullanıcıID");

                    b.ToTable("İhtiyaçlar");

                    b.HasData(
                        new
                        {
                            İhtiyaçID = 1,
                            FrekansID = 4,
                            KayıtTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 12,
                            İhtiyaçAdı = "Ev",
                            İhtiyaçAçıklaması = "Market"
                        },
                        new
                        {
                            İhtiyaçID = 2,
                            FrekansID = 1,
                            KayıtTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 17,
                            İhtiyaçAdı = "Okul",
                            İhtiyaçAçıklaması = "Kırtasiye"
                        },
                        new
                        {
                            İhtiyaçID = 3,
                            FrekansID = 4,
                            KayıtTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 16,
                            İhtiyaçAdı = "Ev",
                            İhtiyaçAçıklaması = "Fatura"
                        },
                        new
                        {
                            İhtiyaçID = 4,
                            FrekansID = 3,
                            KayıtTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 57,
                            İhtiyaçAdı = "Ev",
                            İhtiyaçAçıklaması = "Market"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.İletişim", b =>
                {
                    b.Property<int>("İletişimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("İletişimID"), 1L, 1);

                    b.Property<int>("KullanıcıID")
                        .HasColumnType("int");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("İletişimAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("İletişimID");

                    b.HasIndex("KullanıcıID");

                    b.ToTable("İletişimler");

                    b.HasData(
                        new
                        {
                            İletişimID = 1,
                            KullanıcıID = 12,
                            TelefonNo = "05303303030",
                            İletişimAdı = "ev"
                        },
                        new
                        {
                            İletişimID = 2,
                            KullanıcıID = 17,
                            TelefonNo = "05313313131",
                            İletişimAdı = "ev"
                        },
                        new
                        {
                            İletişimID = 3,
                            KullanıcıID = 17,
                            TelefonNo = "05123456789",
                            İletişimAdı = "ev"
                        },
                        new
                        {
                            İletişimID = 4,
                            KullanıcıID = 16,
                            TelefonNo = "05545545454",
                            İletişimAdı = "ev"
                        },
                        new
                        {
                            İletişimID = 5,
                            KullanıcıID = 57,
                            TelefonNo = "05343343434",
                            İletişimAdı = "ev"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Kişi", b =>
                {
                    b.Property<int>("KişiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KişiID"), 1L, 1);

                    b.Property<string>("AD")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CinsiyetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DoğumTarih")
                        .HasColumnType("Date");

                    b.Property<int>("KullanıcıID")
                        .HasColumnType("int");

                    b.Property<string>("SoyAD")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("KişiID");

                    b.HasIndex("CinsiyetID");

                    b.HasIndex("KullanıcıID")
                        .IsUnique();

                    b.ToTable("Kişiler");

                    b.HasData(
                        new
                        {
                            KişiID = 1,
                            AD = "Serdal",
                            CinsiyetID = 1,
                            DoğumTarih = new DateTime(1976, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 12,
                            SoyAD = "Tanrıverdi"
                        },
                        new
                        {
                            KişiID = 2,
                            AD = "İlhan",
                            CinsiyetID = 1,
                            DoğumTarih = new DateTime(1991, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 17,
                            SoyAD = "Gündoğdu"
                        },
                        new
                        {
                            KişiID = 3,
                            AD = "Reyhan",
                            CinsiyetID = 2,
                            DoğumTarih = new DateTime(1993, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 16,
                            SoyAD = "Balta"
                        },
                        new
                        {
                            KişiID = 4,
                            AD = "Ceren",
                            CinsiyetID = 2,
                            DoğumTarih = new DateTime(2012, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KullanıcıID = 57,
                            SoyAD = "Bıçak"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Kullanıcı", b =>
                {
                    b.Property<int>("KullanıcıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullanıcıID"), 1L, 1);

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("Şifre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KullanıcıID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanıcılar");

                    b.HasData(
                        new
                        {
                            KullanıcıID = 1,
                            Eposta = "sinan@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 2,
                            Eposta = "ali@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 3,
                            Eposta = "mahmut@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 4,
                            Eposta = "mansurkürşad@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 5,
                            Eposta = "gamze@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 6,
                            Eposta = "miraç@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 7,
                            Eposta = "yücel@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 8,
                            Eposta = "kubilay@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 9,
                            Eposta = "hayati@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 10,
                            Eposta = "bedriyemüge@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 11,
                            Eposta = "birsen@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 12,
                            Eposta = "serdal@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 13,
                            Eposta = "bünyamin@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 14,
                            Eposta = "özgür@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 15,
                            Eposta = "ferdi@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 16,
                            Eposta = "reyhan@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 17,
                            Eposta = "ilhan@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 18,
                            Eposta = "gülşah@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 19,
                            Eposta = "nalan@outlook.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 20,
                            Eposta = "semih@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 21,
                            Eposta = "ergün@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 22,
                            Eposta = "fatih@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 23,
                            Eposta = "şenay@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 24,
                            Eposta = "serkan@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 25,
                            Eposta = "emre@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 26,
                            Eposta = "bahattin@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 27,
                            Eposta = "irazca@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 28,
                            Eposta = "hatice@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 29,
                            Eposta = "bariş@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 30,
                            Eposta = "rezan@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 31,
                            Eposta = "fatih@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 32,
                            Eposta = "fuat@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 33,
                            Eposta = "gökhan@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 34,
                            Eposta = "orhan@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 35,
                            Eposta = "mehmet@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 36,
                            Eposta = "evren@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 37,
                            Eposta = "oktay@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 38,
                            Eposta = "harun@gmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 39,
                            Eposta = "yavuz@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 40,
                            Eposta = "pinar@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 41,
                            Eposta = "mehmet@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 42,
                            Eposta = "umut@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 43,
                            Eposta = "mesude@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 44,
                            Eposta = "hüseyincahit@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 45,
                            Eposta = "haşimonur@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 46,
                            Eposta = "eyyupsabri@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 47,
                            Eposta = "mustafa@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 48,
                            Eposta = "mustafa@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 49,
                            Eposta = "ufuk@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 50,
                            Eposta = "ahmetali@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 51,
                            Eposta = "mediha@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 52,
                            Eposta = "hasan@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 53,
                            Eposta = "kamil@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 54,
                            Eposta = "nebi@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 55,
                            Eposta = "özcan@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 56,
                            Eposta = "nagihan@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 57,
                            Eposta = "ceren@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 58,
                            Eposta = "serkan@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 59,
                            Eposta = "hasan@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 60,
                            Eposta = "yusufkenan@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 61,
                            Eposta = "çetin@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 62,
                            Eposta = "tarkan@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 63,
                            Eposta = "meralleman@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 64,
                            Eposta = "ergün@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 65,
                            Eposta = "kenanahmet@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 66,
                            Eposta = "ural@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 67,
                            Eposta = "yahya@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 68,
                            Eposta = "bengü@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 69,
                            Eposta = "fatihnazmi@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 70,
                            Eposta = "dilek@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 71,
                            Eposta = "mehmet@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 72,
                            Eposta = "tufanakin@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 73,
                            Eposta = "mehmet@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 74,
                            Eposta = "turgayyilmaz@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 75,
                            Eposta = "güldehen@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 76,
                            Eposta = "gökmen@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 77,
                            Eposta = "bülent@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 78,
                            Eposta = "erol@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 79,
                            Eposta = "bahri@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 80,
                            Eposta = "özenözlem@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 81,
                            Eposta = "selma@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 82,
                            Eposta = "tuğsem@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 83,
                            Eposta = "teslimenazli@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 84,
                            Eposta = "gülçin@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 85,
                            Eposta = "ismail@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 86,
                            Eposta = "murat@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 87,
                            Eposta = "ebru@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 88,
                            Eposta = "tümay@gmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 89,
                            Eposta = "ahmet@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 90,
                            Eposta = "ebru@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 91,
                            Eposta = "hüseyinyavuz@gmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 92,
                            Eposta = "başak@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 93,
                            Eposta = "ayşegül@hotmail.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 94,
                            Eposta = "evrim@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 95,
                            Eposta = "yaser@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 96,
                            Eposta = "ülkü@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 97,
                            Eposta = "özhan@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 98,
                            Eposta = "ufuk@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 99,
                            Eposta = "aksel@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 100,
                            Eposta = "fulya@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 101,
                            Eposta = "burcu@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 102,
                            Eposta = "taylan@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 103,
                            Eposta = "yilmaz@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 104,
                            Eposta = "zeynep@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 105,
                            Eposta = "bayram@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 106,
                            Eposta = "gülay@hotmail.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 107,
                            Eposta = "rabia@outlook.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 108,
                            Eposta = "sevda@outlook.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 109,
                            Eposta = "serhat@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 110,
                            Eposta = "engin@icloud.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 111,
                            Eposta = "asli@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 112,
                            Eposta = "tuba@icloud.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 113,
                            Eposta = "bariş@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 114,
                            Eposta = "sevgi@hotmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 115,
                            Eposta = "kalender@outlook.com",
                            RolID = 3,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 116,
                            Eposta = "halil@icloud.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 117,
                            Eposta = "bilge@icloud.com",
                            RolID = 1,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 118,
                            Eposta = "ferda@gmail.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 119,
                            Eposta = "ezgi@hotmail.com",
                            RolID = 2,
                            Şifre = "Qwe123"
                        },
                        new
                        {
                            KullanıcıID = 120,
                            Eposta = "aysun@outlook.com",
                            RolID = 4,
                            Şifre = "Qwe123"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Rol", b =>
                {
                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("RolAdı")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            RolID = 1,
                            RolAdı = "UserCandidate"
                        },
                        new
                        {
                            RolID = 2,
                            RolAdı = "UserNormal"
                        },
                        new
                        {
                            RolID = 3,
                            RolAdı = "Admin"
                        },
                        new
                        {
                            RolID = 4,
                            RolAdı = "Supervisor"
                        });
                });

            modelBuilder.Entity("DestekApp.Models.Adres", b =>
                {
                    b.HasOne("DestekApp.Models.Kullanıcı", "Kullanıcı")
                        .WithMany("Adresler")
                        .HasForeignKey("KullanıcıID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("DestekApp.Models.İhtiyaç", b =>
                {
                    b.HasOne("DestekApp.Models.Frekans", "Frekans")
                        .WithMany()
                        .HasForeignKey("FrekansID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DestekApp.Models.Kullanıcı", "Kullanıcı")
                        .WithMany()
                        .HasForeignKey("KullanıcıID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Frekans");

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("DestekApp.Models.İletişim", b =>
                {
                    b.HasOne("DestekApp.Models.Kullanıcı", "Kullanıcı")
                        .WithMany("İletişimler")
                        .HasForeignKey("KullanıcıID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("DestekApp.Models.Kişi", b =>
                {
                    b.HasOne("DestekApp.Models.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DestekApp.Models.Kullanıcı", "Kullanıcı")
                        .WithOne("Kişi")
                        .HasForeignKey("DestekApp.Models.Kişi", "KullanıcıID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinsiyet");

                    b.Navigation("Kullanıcı");
                });

            modelBuilder.Entity("DestekApp.Models.Kullanıcı", b =>
                {
                    b.HasOne("DestekApp.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("DestekApp.Models.Kullanıcı", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Kişi");

                    b.Navigation("İletişimler");
                });
#pragma warning restore 612, 618
        }
    }
}
